import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/user/info">userInfo /</Link>
        <Link href="/user/register">register /</Link>
        <Link href="/user/login">login /</Link>
        <Link href="/funding/create">create /</Link>
        <Link href="/funding/apply">apply /</Link>
        <Link href="/funding/payment">payment</Link>
        {children}
      </body>
    </html>
  );
}
